name: Willboosterify
on:
  workflow_dispatch:
  schedule:
    - cron: 37 13 * * *
permissions:
  contents: write
jobs:
  wbfy:
    uses: WillBooster/reusable-workflows/.github/workflows/wbfy.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
